spring:
  application:
    name: gateway-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
