spring:
  application:
    name: discovery-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false