eureka:
  client:
    service-url:
      defaultZone: "http://localhost:9999/eureka/"
  instance:
    hostname: localhost
    prefer-ip-address: false
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

jwt:
  secret-key: "CLOCKSHOP_SECRET_KEY_SUPER_SECURE_64"