server:
  port: 8080
  servlet:
    context-path: /

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-route
          uri: lb://account-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1