server:
  port: 8080
  servlet:
    context-path: /

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080, http://localhost:5173" # Chỉ định domain cụ thể
            allowedMethods: "*"  # Cho phép tất cả phương thức (GET, POST, PUT, DELETE, ...)
            allowedHeaders: "*"  # Chấp nhận tất cả header
            allowCredentials: true  # Hỗ trợ cookie, authentication
      discovery:
        locator:
          enabled: true

      routes:
        - id: account-route
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1

        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

        - id: received-route
          uri: lb://received-service
          predicates:
            - Path=/received-service/**
          filters:
            - StripPrefix=1
#
        - id: openapi
          uri: lb://gateway-service
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<service>.*), /${service}/v3/api-docs