spring:
  application:
    name: product-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true
#  Upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/static/ # Tìm trong /static và thư mục upload
  mvc:
    static-path-pattern: /images/** # URL pattern để truy cập
file:
  upload-dir: src/main/resources/static/
