# services:
#   config-service:
#     build:
#       context: config-service
#       dockerfile: Dockerfile
#     image: config-service
#     container_name: config-service
#     ports:
#       - 8888:8888

#   discovery-service:
#     build:
#       context: discovery-service
#       dockerfile: Dockerfile
#     image: discovery-service
#     container_name: discovery-service
#     ports:
#       - 9999:9999
#     restart: on-failure
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888

#   gateway-service:
#     build:
#       context: gateway-service
#       dockerfile: Dockerfile
#     image: gateway-service
#     container_name: gateway-service
#     ports:
#       - 8080:8080
#     restart: on-failure
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/

# #  db:
# #    image: mysql:8.0
# #    container_name: mysql_db
# ##    restart: always
# #    environment:
# #      MYSQL_DATABASE: account_service
# #      MYSQL_ROOT_PASSWORD: 123456
# #    ports:
# #      - 3306:3306
# #    healthcheck:
# #      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
# #      interval: 10s
# #      retries: 5
# #      start_period: 30s

#   db:
#     image: mysql:8.0
#     container_name: mysql_db
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#     ports:
#       - 3306:3306
#     volumes:
#       - ./init-scripts:/docker-entrypoint-initdb.d
#     healthcheck:
#       test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#       interval: 10s
#       retries: 5
#       start_period: 30s

#   account-service:
#     build:
#       context: account-service
#       dockerfile: Dockerfile
#     image: account-service
#     container_name: account-service
#     ports:
#       - 8081:8081
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/account_service
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=123456
#     depends_on:
#       db:
#         condition: service_healthy

#   auth-service:
#     build:
#       context: auth-service
#       dockerfile: Dockerfile
#     image: auth-service
#     container_name: auth-service
#     ports:
#       - 8086:8086
#     restart: on-failure
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/

#   product-service:
#     build:
#       context: product-service
#       dockerfile: Dockerfile
#     image: product-service
#     container_name: product-service
#     ports:
#       - 8082:8082
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product_service
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=123456
#     depends_on:
#       db:
#         condition: service_healthy

#   order-service:
#     build:
#       context: order-service
#       dockerfile: Dockerfile
#     image: order-service
#     container_name: order-service
#     ports:
#       - 8083:8083
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/order_service
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=123456
#     depends_on:
#       db:
#         condition: service_healthy

#   received-service:
#     build:
#       context: received-service
#       dockerfile: Dockerfile
#     image: received-service
#     container_name: received-service
#     ports:
#       - 8085:8085
#     environment:
#       - CONFIG_SERVER_URL=http://config-service:8888
#       - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
#       - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/received_service
#       - SPRING_DATASOURCE_USERNAME=root
#       - SPRING_DATASOURCE_PASSWORD=123456
#     depends_on:
#       db:
#         condition: service_healthy

services:
  config-service:
    build:
      context: config-service
      dockerfile: Dockerfile
    image: config-service
    container_name: config-service
    ports:
      - 8888:8888

  discovery-service:
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discovery-service
    container_name: discovery-service
    ports:
      - 9999:9999
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888

  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gateway-service
    container_name: gateway-service
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/

  monitor-admin:
    build:
      context: monitor-admin
      dockerfile: Dockerfile
    image: monitor-admin
    container_name: monitor-admin
    ports:
      - 9001:9001
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s

  # account-service:
  #   build:
  #     context: account-service
  #     dockerfile: Dockerfile
  #   image: account-service
  #   container_name: account-service
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - CONFIG_SERVER_URL=http://config-service:8888
  #     - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/account_service
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=123456
  #   depends_on:
  #     db:
  #       condition: service_healthy


  account-service:
    build:
      context: account-service
      dockerfile: Dockerfile
    image: account-service:latest
    container_name: account-service
    ports:
      - 8081:8081
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/account_service  # Dùng chung
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  account-service-port2:
    build:
      context: account-service
      dockerfile: Dockerfile
    image: account-service:latest      # Dùng chung image đã build ở trên
    container_name: account-service-port2
    ports:
      - 9081:9081
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/account_service  # Dùng chung
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_PROFILES_ACTIVE=port2   # Kích hoạt profile 'port2'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: auth-service
    container_name: auth-service
    ports:
      - 8086:8086
    restart: on-failure
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/

  product-service:
    build:
      context: product-service
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    ports:
      - 8082:8082
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      db:
        condition: service_healthy

  order-service:
    build:
      context: order-service
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service
    ports:
      - 8083:8083
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/order_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      db:
        condition: service_healthy

  received-service:
    build:
      context: received-service
      dockerfile: Dockerfile
    image: received-service
    container_name: received-service
    ports:
      - 8085:8085
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-service:9999/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/received_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      db:
        condition: service_healthy